### PR TITLE
Music Docs

### PR DESCRIPTION
**Pull request by TheOfficialDoc**
You can remove Created by Doc if you want.
Also checkout the compiling pull request.

### CODE REVIEW

**Comment by TheOfficialDoc** [comment]
About readme.md updates that was probably commit from my exporer. It does not affect latest readme. Infact its same.

**Comment by SilBoydens** [comment]
some grammer errors(really stupid once like dubble letters where there should only be one)
and not clickable links, i will merge and fix it tomorow when i am on my pc

**Comment by BLUUUUUE** [comment]
can i try fixing them with my new grammar detection system

**Comment by TheOfficialDoc** [comment]
Sure you can

**Comment by Cat-who-loves-bots** [comment]
you can pull searched all music.md file

**Pull request merged**
