### PR TITLE
make it nice

### PR DESCRIPTION
**Pull request by BLUUUUUE**
i will now try finding for all other stuff badges to make it nice

### CODE REVIEW

**Comment by BLUUUUUE** [comment]
and those badges are for this git not mee6

**Comment by BLUUUUUE** [comment]
i will make those for Mee6 git to

**Comment by SilBoydens** [comment]
why do we need a link to W3schools and javascript.com? i don't get it.

**Comment by BLUUUUUE** [comment]
meh we can remove that if needed

**Comment by BLUUUUUE** [comment]
removing that now

**Comment by BLUUUUUE** [comment]
done

**Comment by BLUUUUUE** [comment]
should be all now

**Comment by BLUUUUUE** [comment]
[hey]()

**Pull request merged**
